### POST
POST http://localhost:8000/api_generate_token/
Content-Type: application/json

{
  "username": "admin",
  "password":  "1234"
}

### POST
POST http://localhost:8000/api_generate_token/
Content-Type: application/json

{
  "username": "andres",
  "password":  "190308022014aj"
}